app: techxi
http_port: 8080
base_url: http://localhost:8080/
db_connection_string: mongodb+srv://techxi:PkxToEvPlokENJ2C@techxi.va8r7de.mongodb.net/techxi?retryWrites=true&w=majority
token_secret: nhatminhdepzaivaicaloz
auth_jwt: 1
rabbitmq_url: amqps://qgkfypdz:bpDTputLB1EzSTiB0N5Of_OvINBuX8Yq@armadillo.rmq.cloudamqp.com/qgkfypdz
  # callcenter: 0
  # driver: 0
  # admin: 0
map_services:
  google_map_api_key: AIzaSyCOCXMJVWCATqhrs41VKk7hWX9MQQowkVg
  street_map_api_key: street_map
  mapbox_api_key: sk.eyJ1IjoibmRhbjIwIiwiYSI6ImNsbHV5NHRjZzFpanQzanB2OTNoNm9yZW8ifQ.N23CjaLqNAl0StkRP1A1rw